# Generated by Django 5.0 on 2023-12-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinique', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='departement',
            field=models.CharField(default='Département Temporaire', max_length=50),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='departement',
            field=models.CharField(default='Département Temporaire', max_length=50),
        ),
    ]
