# Generated by Django 5.0 on 2023-12-30 17:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinique', '0002_medecin_departement_rendezvous_departement'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeRdv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=10)),
                ('prenom', models.CharField(max_length=10)),
                ('tel', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit contenir 10 chiffres commançant par 05 ou 06 ou 07.', regex='^(05|06|07)[0-9]{8}$')])),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('Departement', models.CharField(max_length=10)),
                ('sujet', models.CharField(max_length=250)),
            ],
        ),
    ]
