# Generated by Django 5.0.1 on 2024-01-26 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinique', '0003_demanderdv'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActeMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Chirurgie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('posologie', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionMedicale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acte_medical', models.ManyToManyField(blank=True, null=True, to='clinique.actemedical')),
                ('chirurgie', models.ManyToManyField(blank=True, to='clinique.chirurgie')),
                ('medicaments', models.ManyToManyField(to='clinique.medicament')),
            ],
        ),
        migrations.CreateModel(
            name='SalleOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DemandeRdv',
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='sujet',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinique.departement'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nss',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinique.departement'),
        ),
        migrations.AddField(
            model_name='prescriptionmedicale',
            name='rendezvous',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clinique.rendezvous'),
        ),
    ]
