# Generated by Django 5.0.1 on 2024-01-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinique', '0004_actemedical_chirurgie_medicament_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='adresse',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptionmedicale',
            name='acte_medical',
            field=models.ManyToManyField(blank=True, to='clinique.actemedical'),
        ),
    ]
