# Generated by Django 5.0.1 on 2024-01-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinique', '0005_patient_adresse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='sexe',
            field=models.CharField(choices=[('F', 'Féminin'), ('M', 'Masculin')], default='F', max_length=1),
        ),
    ]
