# Generated by Django 5.0 on 2024-01-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinique', '0006_patient_sexe'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
