# Generated by Django 5.0 on 2024-01-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinique', '0009_compte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='compte',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
