# Generated by Django 5.0 on 2024-01-27 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinique', '0010_alter_compte_email_alter_compte_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='demRendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('sujet', models.TextField(default='')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinique.departement')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinique.patient')),
            ],
        ),
    ]
