# Generated by Django 5.0 on 2024-01-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinique', '0011_demrendezvous'),
    ]

    operations = [
        migrations.AddField(
            model_name='compte',
            name='est_medecin',
            field=models.BooleanField(default=False),
        ),
    ]
