# Generated by Django 5.0 on 2024-01-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinique', '0012_compte_est_medecin'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='password',
            field=models.CharField(default='admin', max_length=128),
        ),
    ]
