# Generated by Django 5.0 on 2024-01-28 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinique', '0013_medecin_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous_set', to='clinique.patient'),
        ),
    ]
