# Generated by Django 5.0 on 2024-01-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinique', '0014_alter_rendezvous_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossiermedical',
            name='description',
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='allergies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='antecedents_medicaux',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='notes_supplementaires',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='rhesus_sanguin',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='traitements_en_cours',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salleoperation',
            name='nom',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
